export default function Legal() {
  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400&display=swap');

        body { background: #1a1d2e; color: #e8e6e1; margin: 0; }

        .legal-wrap {
          max-width: 720px;
          margin: 0 auto;
          padding: 120px 8vw 100px;
          font-family: -apple-system, sans-serif;
        }

        .legal-nav {
          position: fixed; top: 0; left: 0; right: 0; z-index: 100;
          padding: 1.4rem 8vw;
          display: flex; align-items: center; justify-content: space-between;
          background: rgba(26,29,46,0.92); backdrop-filter: blur(12px);
          border-bottom: 1px solid rgba(200,169,110,0.12);
        }
        .legal-nav-brand {
          font-family: -apple-system, sans-serif; font-size: 0.72rem;
          font-weight: 600; letter-spacing: 0.25em; text-transform: uppercase;
          color: #c8a96e; text-decoration: none;
        }
        .legal-nav-back {
          font-family: -apple-system, sans-serif; font-size: 0.72rem;
          letter-spacing: 0.1em; color: rgba(232,230,225,0.45);
          text-decoration: none; transition: color 0.15s;
        }
        .legal-nav-back:hover { color: #c8a96e; }

        .legal-label {
          font-size: 0.65rem; font-weight: 600;
          letter-spacing: 0.2em; text-transform: uppercase;
          color: #c8a96e; margin-bottom: 1.5rem;
        }

        .legal-title {
          font-family: 'Cormorant Garamond', Georgia, serif;
          font-size: clamp(2rem, 3.5vw, 3rem);
          font-weight: 400; color: #e8e6e1;
          line-height: 1.1; margin-bottom: 0.75rem;
        }

        .legal-meta {
          font-size: 0.8rem; color: rgba(232,230,225,0.35);
          letter-spacing: 0.06em; margin-bottom: 4rem;
        }

        .legal-section {
          margin-bottom: 3rem;
          padding-bottom: 3rem;
          border-bottom: 1px solid rgba(200,169,110,0.12);
        }
        .legal-section:last-of-type { border-bottom: none; }

        .legal-section h2 {
          font-family: -apple-system, sans-serif;
          font-size: 0.7rem; font-weight: 600;
          letter-spacing: 0.18em; text-transform: uppercase;
          color: #c8a96e; margin-bottom: 1.25rem;
        }

        .legal-section p {
          font-size: 0.95rem; line-height: 1.85;
          color: rgba(232,230,225,0.7);
          margin-bottom: 1rem;
        }
        .legal-section p:last-child { margin-bottom: 0; }

        .legal-section a {
          color: #c8a96e; text-decoration: none;
          border-bottom: 1px solid rgba(200,169,110,0.3);
        }
        .legal-section a:hover { border-bottom-color: #c8a96e; }

        .legal-footer {
          margin-top: 5rem;
          padding-top: 2rem;
          border-top: 1px solid rgba(200,169,110,0.1);
          font-size: 0.72rem;
          color: rgba(232,230,225,0.25);
          letter-spacing: 0.06em;
          display: flex; justify-content: space-between;
        }
      `}</style>

      <nav className="legal-nav">
        <a href="/" className="legal-nav-brand">DA SUITE</a>
        <a href="/" className="legal-nav-back">← Back</a>
      </nav>

      <div className="legal-wrap">
        <div className="legal-label">Legal Notice</div>
        <h1 className="legal-title">Terms, Privacy &amp; Disclaimers</h1>
        <p className="legal-meta">Effective April 2026 &nbsp;·&nbsp; Maria v. Heland / Tindra Film, Berlin</p>

        <div className="legal-section">
          <h2>AI-Generated Content</h2>
          <p>All outputs from DA SUITE tools are generated by artificial intelligence for creative development purposes only. They do not constitute legal, financial, or professional advice. AI outputs may contain errors or outdated information and should be independently verified before being relied upon.</p>
        </div>

        <div className="legal-section">
          <h2>Your Content</h2>
          <p>You retain full ownership of everything you submit — scripts, treatments, loglines, budget data, and all other material. No content is intentionally retained by DA SUITE after your session ends. Submitting content to any DA SUITE tool does not transfer, license, or assign any intellectual property rights to the operator.</p>
        </div>

        <div className="legal-section">
          <h2>Data Processing</h2>
          <p>Text submitted to AI-powered tools is processed by Anthropic, Inc. (USA) via their Claude API, and hosted on Vercel, Inc. DA SUITE does not store your content. Anthropic does not use API inputs for model training by default — see <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer">anthropic.com/privacy</a>.</p>
          <p>This processing involves a transfer of data to the United States under standard contractual clauses. The lawful basis for this processing is legitimate interests (Art. 6(1)(f) GDPR). If you are located in the EU or EEA and have questions about your data rights, contact us at the address below.</p>
        </div>

        <div className="legal-section">
          <h2>GUIDA — Treaty Intelligence</h2>
          <p>GUIDA provides co-production treaty and eligibility information for orientation and research purposes only. AI outputs may not reflect current treaty terms or regulatory changes. This is not legal advice. Verify all treaty-related information with a qualified co-production specialist or entertainment lawyer before use in financing documentation.</p>
        </div>

        <div className="legal-section">
          <h2>AYDA — Budget Intelligence</h2>
          <p>AYDA provides budget modelling and incentive research for reference and development purposes only. AI outputs may not reflect current incentive rates or territory-specific conditions. This is not financial advice. Verify all figures with a qualified line producer or accountant before use in financing documentation.</p>
        </div>

        <div className="legal-section">
          <h2>Limitation of Liability</h2>
          <p>To the maximum extent permitted by applicable law, Maria v. Heland / Tindra Film shall not be liable for any direct, indirect, incidental, or consequential loss arising from the use of, or reliance on, any DA SUITE tool or its AI-generated outputs.</p>
        </div>

        <div className="legal-section">
          <h2>Contact</h2>
          <p>Maria v. Heland / Tindra Film, Berlin, Germany.<br />
          For data protection enquiries: <a href="mailto:maria@tindrafilm.com">maria@tindrafilm.com</a></p>
        </div>

        <div className="legal-section">
          <h2>Governing Law</h2>
          <p>These terms are governed by the laws of Germany. Any disputes shall be subject to the exclusive jurisdiction of the courts of Berlin, Germany.</p>
        </div>

        <footer className="legal-footer">
          <span>DA SUITE &nbsp;·&nbsp; dasuite.mov</span>
          <span>Maria v. Heland &nbsp;·&nbsp; 2026</span>
        </footer>
      </div>
    </>
  );
}
